@startuml
left to right direction

actor Robot
actor "Management System" as ms

usecase "check battery" as cb
usecase "complete task" as ct

Robot - ct : "does task"
ms - ct : "assigns task if robot has enough battery"
Robot - cb
ms - cb




@enduml