@startuml

actor Robot

usecase "check type" as ct
usecase "check size" as cs
usecase "assigns task" as at
usecase "does task" as dt

actor Customer

Customer - at
at - cs
at - ct
ct - dt : "right type?"
cs - dt : "right size?"
dt - Robot

@enduml

'As a robot I need to be able to know my own type (a large robot or a small one ).